---
meta:
  data_dir: "./data/annotated_data"
  save_model_dir: "app/checkpoints"
  dataset_splits: [0.7,0.9]
  initial_seed: 1
  num_seeds:  5
wandb_config:
  entity: "j-getzner"
  project: "Trends & Innovations Classifier"
  disabled: False
transformer_config:
  model_name: "distilbert-base-uncased"
  num_labels: 17
  epochs: 10
  lr: 0.0001
  patience: 3
  batch_sizes:
    train: 5
    val: 5
    test: 5