name: tandic-training
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - torch
    - torchvision
    - torchmetrics
    - matplotlib
    - scikit-learn
    - pandas
    - tqdm
    - wandb
    - numpy
    - transformers
    - python-dotenv
    - PyYAML