name: trends-innovations-classifier
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - torchvision
    - torchmetrics
    - matplotlib
    - scikit-learn
    - pandas
    - tqdm
    - wandb
    - numpy
    - transformers
    - python-dotenv