---
# top 50 categories by precision
top-50-by-precision-distilbert:
  model_name: "distilbert-base-uncased"
  lr: 0.00005
  num_warmup_steps: 500
  wandb:
    job_type_modifier: ""
    group_name_modifier: ""
  skip: False
  num_seeds: 5
  min_samples_per_label: 1
  only_top_n_categories_by: ["precision", 50]

# baseline
baseline-distilbert:
  model_name: "distilbert-base-uncased"
  lr: 0.00005
  num_warmup_steps: 500
  wandb:
    job_type_modifier: ""
    group_name_modifier: ""
  skip: False
  num_seeds: 5