---
baseline-roberta-base:
  model_name: "roberta-base"
  lr: 0.00005
  num_warmup_steps: 500
  wandb:
    job_type_modifier: ""
    group_name_modifier: ""
baseline-albert-base-v2:
  model_name: "albert-base-v2"
  lr: 0.00002
  num_warmup_steps: 500
  wandb:
    job_type_modifier: ""
    group_name_modifier: ""