---
# top 10 categories by precision
top-10-by-precision-distilbert:
  model_name: "distilbert-base-uncased"
  lr: 0.00005
  num_warmup_steps: 500
  wandb:
    job_type_modifier: ""
    group_name_modifier: ""
  skip: False
  num_seeds: 5
  min_samples_per_label: 1
  only_top_n_categories_by: ["precision", 10]

# top 30 categories by precision
top-30-by-precision-distilbert:
  model_name: "distilbert-base-uncased"
  lr: 0.00005
  num_warmup_steps: 500
  wandb:
    job_type_modifier: ""
    group_name_modifier: ""
  skip: False
  num_seeds: 5
  min_samples_per_label: 1
  only_top_n_categories_by: ["precision", 30]

# top 50 categories by precision
top-50-by-precision-distilbert:
  model_name: "distilbert-base-uncased"
  lr: 0.00005
  num_warmup_steps: 500
  wandb:
    job_type_modifier: ""
    group_name_modifier: ""
  skip: False
  num_seeds: 5
  min_samples_per_label: 1
  only_top_n_categories_by: ["precision", 50]

# top 10 categories by f1
top-10-by-f1-distilbert:
  model_name: "distilbert-base-uncased"
  lr: 0.00005
  num_warmup_steps: 500
  wandb:
    job_type_modifier: ""
    group_name_modifier: ""
  skip: False
  num_seeds: 5
  min_samples_per_label: 1
  only_top_n_categories_by: ["f1", 10]

# top 30 categories by f1
top-30-by-f1-distilbert:
  model_name: "distilbert-base-uncased"
  lr: 0.00005
  num_warmup_steps: 500
  wandb:
    job_type_modifier: ""
    group_name_modifier: ""
  skip: False
  num_seeds: 5
  min_samples_per_label: 1
  only_top_n_categories_by: ["f1", 30]

# top 50 categories by f1
top-50-by-f1-distilbert:
  model_name: "distilbert-base-uncased"
  lr: 0.00005
  num_warmup_steps: 500
  wandb:
    job_type_modifier: ""
    group_name_modifier: ""
  skip: False
  num_seeds: 3
  min_samples_per_label: 1
  only_top_n_categories_by: ["f1", 50]

# baseline
baseline-distilbert:
  model_name: "distilbert-base-uncased"
  lr: 0.00005
  num_warmup_steps: 500
  wandb:
    job_type_modifier: ""
    group_name_modifier: ""
  skip: False
  num_seeds: 5